'use client'
/* eslint-disable react-hooks/refs -- dnd-kit exposes callback refs and reactive drag state as hook return values. */

import { DndContext, KeyboardSensor, PointerSensor, pointerWithin, useDraggable, useDroppable, useSensor, useSensors, type DragEndEvent } from '@dnd-kit/core'
import { sortableKeyboardCoordinates } from '@dnd-kit/sortable'
import { useDocumentInfo, useField, useForm } from '@payloadcms/ui'
import { useEffect, useRef, useState } from 'react'
import { insertTemplateNode, moveTemplateNode, moveTemplateNodeTo, removeTemplateNode, updateTemplateNode } from '../template-tree'
import type { FieldDefinition, ID, TemplateBlockNode, TemplateField, TemplateFieldKind, TemplateLayoutKind, TemplateLayoutNode, TemplateNode } from '../types'

type BlockTypeOption = { id: ID; name: string; description?: string; rendererKey?: string; fields?: FieldDefinition[] }
type DesignOption = { id: ID; name: string; blockType: ID }
type Impact = { collection: string; id: ID; status?: string }
type LegacySection = { key: string; name: string; blockType: ID; blockDesign: ID }
type LibraryItem = { kind: 'layout' | 'field' | 'block'; value: string; label: string }
let pendingLibraryPointerItem: LibraryItem | null = null

const layoutItems: LibraryItem[] = ['container', 'row', 'columns', 'stack', 'spacer', 'divider'].map((value) => ({ kind: 'layout', value, label: value[0].toUpperCase() + value.slice(1) }))
const fieldItems: LibraryItem[] = [
  ['shortText', 'Short Text'], ['longText', 'Long Text'], ['richText', 'Rich Text'], ['image', 'Image'], ['images', 'Images / Gallery'], ['videoURL', 'Video URL'], ['link', 'URL / Link'], ['date', 'Date'], ['number', 'Number'], ['select', 'Select'], ['toggle', 'Toggle'], ['relationship', 'Relationship'],
].map(([value, label]) => ({ kind: 'field', value, label }))
const panel = { border: '1px solid var(--theme-elevation-150)', borderRadius: 8, padding: '1rem' } as const
const relationID = (value: unknown): ID | undefined => typeof value === 'string' || typeof value === 'number' ? value : value && typeof value === 'object' && 'id' in value ? (value as { id?: ID }).id : undefined
const uid = (prefix: string) => `${prefix}_${crypto.randomUUID()}`
async function fetchDocs<T>(url: string): Promise<T[]> { const response = await fetch(url, { credentials: 'same-origin' }); if (!response.ok) return []; const body = await response.json() as { docs?: T[] }; return body.docs ?? [] }

function LibraryButton({ item, add }: { item: LibraryItem; add: () => void }) {
  return <div style={{ display: 'flex', gap: 4, marginBottom: 4 }}><button type="button" draggable aria-label={`Drag ${item.label}`} onPointerDown={() => { pendingLibraryPointerItem = item }} onPointerUp={() => { pendingLibraryPointerItem = null }} onDragStart={(event) => { const serialized = JSON.stringify(item); event.dataTransfer.effectAllowed = 'copy'; event.dataTransfer.setData('application/x-template-library', serialized); event.dataTransfer.setData('text/plain', serialized) }} style={{ cursor: 'grab', touchAction: 'none' }}>⠿</button><button type="button" onClick={add} style={{ flex: 1, textAlign: 'left' }}>{item.label}</button></div>
}
function DropArea({ id, label, children, add, addItem }: { id: string; label: string; children: React.ReactNode; add?: () => void; addItem?: (item: LibraryItem) => void }) {
  const drop = useDroppable({ id: `container:${id}`, data: { containerID: id } })
  return <div style={{ minHeight: 60, padding: 8, border: '1px solid var(--theme-elevation-150)', borderRadius: 6 }}>
    <div ref={drop.setNodeRef} aria-label={label} onPointerUp={() => { if (pendingLibraryPointerItem && addItem) addItem(pendingLibraryPointerItem); pendingLibraryPointerItem = null }} onDragOver={(event) => { event.preventDefault(); event.dataTransfer.dropEffect = 'copy' }} onDrop={(event) => { const value = event.dataTransfer.getData('application/x-template-library') || event.dataTransfer.getData('text/plain'); if (!value || !addItem) return; event.preventDefault(); pendingLibraryPointerItem = null; try { addItem(JSON.parse(value) as LibraryItem) } catch { /* ignore invalid external drag data */ } }} style={{ minHeight: 42, display: 'grid', placeItems: 'center', marginBottom: 8, border: `2px dashed ${drop.isOver ? 'var(--theme-success-500)' : 'var(--theme-elevation-250)'}`, background: drop.isOver ? 'var(--theme-success-50)' : undefined, borderRadius: 6, fontSize: 13 }}>{drop.isOver ? 'Release to add here' : 'Drop element here'}</div>
    {add && <button type="button" aria-label={`Add element to ${label}`} onClick={add} style={{ width: '100%', marginBottom: 8 }}>＋ Add element</button>}
    {children}
  </div>
}
type TreeActions = { edit: (node: TemplateNode) => void; move: (id: string, direction: -1 | 1) => void; remove: (id: string) => void; add: (containerID: string) => void; addItem: (item: LibraryItem, containerID: string) => void }
function Tree({ nodes, actions }: { nodes: TemplateNode[]; actions: TreeActions }) { return <div style={{ display: 'grid', gap: 8 }}>{nodes.map((node) => <CanvasNode key={node.id} node={node} siblings={nodes} actions={actions} />)}</div> }
function CanvasNode({ node, siblings, actions }: { node: TemplateNode; siblings: TemplateNode[]; actions: TreeActions }) {
  const drag = useDraggable({ id: `node:${node.id}`, data: { nodeID: node.id } }); const index = siblings.findIndex((item) => item.id === node.id)
  const title = node.type === 'field' ? node.label : node.type === 'block' ? node.name : node.layout
  const controls = <div style={{ display: 'flex', gap: 4, flexWrap: 'wrap' }}><button type="button" {...drag.listeners} {...drag.attributes} aria-label={`Drag ${title}`}>⠿</button><button type="button" onClick={() => actions.edit(node)}>Edit</button><button type="button" disabled={index <= 0} onClick={() => actions.move(node.id, -1)}>Move Up</button><button type="button" disabled={index === siblings.length - 1} onClick={() => actions.move(node.id, 1)}>Move Down</button><button type="button" onClick={() => actions.remove(node.id)}>Remove</button></div>
  if (node.type === 'field') return <article ref={drag.setNodeRef} style={panel}><strong>{node.label}</strong><p>{fieldItems.find((item) => item.value === node.fieldType)?.label}{node.required ? ' · Required' : ''}</p>{controls}</article>
  if (node.type === 'block') return <article ref={drag.setNodeRef} style={panel}><strong>{node.name}</strong><p>Designed Block · {node.fields.length} mapped field{node.fields.length === 1 ? '' : 's'}</p>{controls}</article>
  return <article ref={drag.setNodeRef} style={panel}><strong>{node.layout === 'columns' ? `Columns · ${node.columns?.map((column) => column.width).join(' / ')}` : title}</strong>{controls}{node.layout === 'columns' ? <div style={{ display: 'grid', gridTemplateColumns: node.columns?.map((column) => `${column.width}fr`).join(' '), gap: 8, marginTop: 8 }}>{node.columns?.map((column, i) => <DropArea key={column.id} id={column.id} label={`Column ${i + 1}`} add={() => actions.add(column.id)} addItem={(item) => actions.addItem(item, column.id)}><Tree nodes={column.children} actions={actions} /></DropArea>)}</div> : !['spacer', 'divider'].includes(node.layout) ? <div style={{ marginTop: 8 }}><DropArea id={node.id} label={`${node.layout} contents`} add={() => actions.add(node.id)} addItem={(item) => actions.addItem(item, node.id)}><Tree nodes={node.children ?? []} actions={actions} /></DropArea></div> : null}</article>
}

export function TemplateBuilder({ configuredCollections = ['posts'], registeredRendererKeys = ['hero-board'] }: { configuredCollections?: string[]; registeredRendererKeys?: string[] }) {
  const { id, hasPublishedDoc } = useDocumentInfo(); const { submit, disabled } = useForm()
  const nameField = useField<string>({ path: 'name' }); const descriptionField = useField<string>({ path: 'description' }); const slugField = useField<string>({ path: 'slug' }); const collectionsField = useField<string[]>({ path: 'allowedCollections' }); const layoutField = useField<TemplateNode[]>({ path: 'layout' }); const sectionsField = useField<LegacySection[]>({ path: 'sections' }); const statusField = useField<string>({ path: '_status' })
  const name = nameField.value ?? ''; const collections = Array.isArray(collectionsField.value) ? collectionsField.value : []; const nodes = Array.isArray(layoutField.value) ? layoutField.value : []; const legacy = Array.isArray(sectionsField.value) ? sectionsField.value : []
  const [types, setTypes] = useState<BlockTypeOption[]>([]); const [designs, setDesigns] = useState<DesignOption[]>([]); const [impact, setImpact] = useState<Impact[]>([]); const [editing, setEditing] = useState<TemplateNode | null>(null); const [adding, setAdding] = useState<LibraryItem | null>(null); const [target, setTarget] = useState('root'); const [libraryTarget, setLibraryTarget] = useState('root'); const [libraryOpen, setLibraryOpen] = useState(true); const [error, setError] = useState<string | null>(null)
  const modified = useRef(false); const sensors = useSensors(useSensor(PointerSensor), useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates }))
  useEffect(() => { Promise.all([
    fetchDocs<BlockTypeOption>('/api/design-block-types?depth=0&limit=100&where[status][equals]=published&where[_status][equals]=published'),
    fetchDocs<DesignOption>('/api/design-block-designs?depth=0&limit=100&where[status][equals]=published&where[_status][equals]=published'),
  ]).then(([typeDocs, designDocs]) => { setTypes(typeDocs.filter((item) => item.rendererKey && registeredRendererKeys.includes(item.rendererKey))); setDesigns(designDocs) }).catch(() => setError('Could not load the registered design library.')) }, [registeredRendererKeys])
  useEffect(() => { if (!id) return
    async function load() { try { const response = await fetch(`/api/design-templates/${id}?draft=true&depth=0`, { credentials: 'same-origin' }); const doc = response.ok ? await response.json() as { layout?: TemplateNode[]; sections?: LegacySection[] } : null; if (!modified.current) { if (Array.isArray(doc?.layout)) layoutField.setValue(doc.layout); if (Array.isArray(doc?.sections)) sectionsField.setValue(doc.sections) } } catch { /* keep current form data */ }
      try { const response = await fetch(`/api/design-templates/${id}/dependencies`, { credentials: 'same-origin' }); const body = response.ok ? await response.json() as Impact[] : []; setImpact(Array.isArray(body) ? body : []) } catch { setImpact([]) } }
    void load()
  }, [id, layoutField, sectionsField])
  const setNodes = (next: TemplateNode[]) => { modified.current = true; layoutField.setValue(next) }
  const startAdd = (item: LibraryItem, container = 'root') => { setAdding(item); setTarget(container); setEditing(null) }
  const openLibraryFor = (containerID: string) => { setLibraryTarget(containerID); setLibraryOpen(true) }
  const actions: TreeActions = { edit: (node) => { setEditing(node); setAdding(null) }, add: openLibraryFor, addItem: (item, containerID) => startAdd(item, containerID), move: (nodeID, direction) => setNodes(moveTemplateNode(nodes, nodeID, direction)), remove: (nodeID) => { if (!hasPublishedDoc || !impact.length || window.confirm(`This Template is used by ${impact.length} content items. Removed field values remain stored. Continue?`)) setNodes(removeTemplateNode(nodes, nodeID)) } }
  function dragEnd(event: DragEndEvent) { const container = event.over?.data.current?.containerID as string | undefined; if (!container) return; const library = event.active.data.current?.library as LibraryItem | undefined; if (library) startAdd(library, container); else { const nodeID = event.active.data.current?.nodeID as string | undefined; if (nodeID) setNodes(moveTemplateNodeTo(nodes, nodeID, container)) } }
  async function save(publish: boolean) { if (!name.trim() || !collections.length) { setError('Name and Use With are required.'); return } await submit({ overrides: { slug: slugField.value || name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''), status: publish ? 'published' : 'draft', _status: publish ? 'published' : 'draft' } }) }
  return <DndContext id="template-builder-dnd" sensors={sensors} collisionDetection={pointerWithin} onDragEnd={dragEnd}><div data-testid="template-builder" style={{ display: 'grid', gap: 16 }}><header><h1>{name || 'Create Template'}</h1><strong>{statusField.value === 'published' ? 'Published' : 'Draft'}</strong>{id && <p>Used by: {impact.length} content item{impact.length === 1 ? '' : 's'}</p>}</header>
    <section style={panel}><label>Name<input aria-label="Name" value={name} onChange={(e) => nameField.setValue(e.target.value)} /></label><label style={{ display: 'block' }}>Description<textarea aria-label="Description" value={descriptionField.value ?? ''} onChange={(e) => descriptionField.setValue(e.target.value)} /></label><fieldset><legend>Use With</legend>{configuredCollections.map((slug) => <label key={slug}><input type="checkbox" checked={collections.includes(slug)} onChange={() => collectionsField.setValue(collections.includes(slug) ? collections.filter((item) => item !== slug) : [...collections, slug])} /> {slug[0].toUpperCase() + slug.slice(1)}</label>)}</fieldset></section>
    <div><button type="button" aria-expanded={libraryOpen} aria-controls="template-element-library" onClick={() => { setLibraryTarget('root'); setLibraryOpen((open) => !open) }}>☰ {libraryOpen ? 'Close' : 'Open'} Element Library</button></div>
    <div style={{ display: 'grid', gridTemplateColumns: `${libraryOpen ? '240px' : '0px'} minmax(420px, 1fr) minmax(280px, 360px)`, gap: 16, alignItems: 'start' }}>
      {libraryOpen && <aside id="template-element-library" style={{ ...panel, position: 'sticky', top: 16, maxHeight: 'calc(100vh - 32px)', overflowY: 'auto' }} aria-label="Element Library"><div style={{ display: 'flex', justifyContent: 'space-between', gap: 8 }}><h2>Element Library</h2><button type="button" aria-label="Close Element Library" onClick={() => setLibraryOpen(false)}>×</button></div><p>Add to: <strong>{libraryTarget === 'root' ? 'Template Canvas' : 'selected container'}</strong></p><h3>Layout</h3>{layoutItems.map((item) => <LibraryButton key={item.value} item={item} add={() => startAdd(item, libraryTarget)} />)}<h3>Fields</h3>{fieldItems.map((item) => <LibraryButton key={item.value} item={item} add={() => startAdd(item, libraryTarget)} />)}<h3>Designed Blocks</h3>{types.map((type) => { const item: LibraryItem = { kind: 'block', value: String(type.id), label: type.name }; return <LibraryButton key={type.id} item={item} add={() => startAdd(item, libraryTarget)} /> })}</aside>}
      <main aria-label="Template Canvas"><h2>Template Canvas</h2><DropArea id="root" label="Template Canvas drop area" add={() => openLibraryFor('root')} addItem={(item) => startAdd(item, 'root')}>{!nodes.length && !legacy.length && <p>Drag an element here or use Add element.</p>}<Tree nodes={nodes} actions={actions} />{legacy.length > 0 && <section><h3>Existing Designed Blocks</h3>{legacy.map((section) => <article key={section.key} style={panel}><strong>{section.name}</strong><p>Legacy live reference retained. Rebuild on the canvas when ready.</p></article>)}</section>}</DropArea></main>
      <aside aria-label="Configure panel" style={{ ...panel, position: 'sticky', top: 16 }}><h2>Configure</h2>{(adding || editing) ? <NodeEditor item={adding} node={editing} types={types} designs={designs} cancel={() => { setAdding(null); setEditing(null) }} create={(node) => { setNodes(insertTemplateNode(nodes, target, node)); setAdding(null); setLibraryTarget('root') }} update={(node) => { setNodes(updateTemplateNode(nodes, node.id, () => node)); setEditing(null) }} /> : <p>Select Edit on an element, drag an item from the library, or use an Add element button.</p>}</aside>
    </div>
    {error && <p role="alert">{error}</p>}<footer><button type="button" disabled={disabled} onClick={() => void save(false)}>Save Draft</button> <button type="button" disabled={disabled} onClick={() => void save(true)}>{hasPublishedDoc ? 'Publish Changes' : 'Publish Template'}</button></footer></div></DndContext>
}

function NodeEditor({ item, node, types, designs, cancel, create, update }: { item: LibraryItem | null; node: TemplateNode | null; types: BlockTypeOption[]; designs: DesignOption[]; cancel: () => void; create: (node: TemplateNode) => void; update: (node: TemplateNode) => void }) {
  const kind = item?.kind ?? node?.type; const value = item?.value ?? (node?.type === 'field' ? node.fieldType : node?.type === 'layout' ? node.layout : node?.type === 'block' ? String(relationID(node.blockType)) : '')
  const [label, setLabel] = useState(node?.type === 'field' ? node.label : item?.label ?? ''); const [required, setRequired] = useState(node?.type === 'field' && !!node.required); const [help, setHelp] = useState(node?.type === 'field' ? node.helpText ?? '' : ''); const [placeholder, setPlaceholder] = useState(node?.type === 'field' ? node.placeholder ?? '' : '')
  const [ratio, setRatio] = useState(node?.type === 'layout' && node.layout === 'columns' ? node.columns?.map((column) => column.width).join('/') ?? '50/50' : '50/50'); const type = types.find((option) => String(option.id) === value); const block = node?.type === 'block' ? node : null
  const [design, setDesign] = useState<ID | ''>(relationID(block?.blockDesign) ?? ''); const [allowOverride, setAllowOverride] = useState(!!block?.allowDesignOverride); const [fields, setFields] = useState<TemplateField[]>(block?.fields ?? []); const [mappings, setMappings] = useState<Record<string, string>>(block?.slotMappings ?? {})
  function finish() { let next: TemplateNode; if (kind === 'layout') { const layout = value as TemplateLayoutKind; next = { id: node?.id ?? uid('layout'), type: 'layout', layout, ...(layout === 'columns' ? { columns: ratio.split('/').map((width) => ({ id: uid('column'), width: Number(width), children: [] as TemplateNode[] })) } : ['spacer', 'divider'].includes(layout) ? {} : { children: node?.type === 'layout' ? node.children ?? [] : [] as TemplateNode[] }) } as TemplateLayoutNode } else if (kind === 'field') next = { id: node?.id ?? uid('field'), type: 'field', fieldType: value as TemplateFieldKind, label: label || item?.label || 'Untitled', required, helpText: help, placeholder } as TemplateField; else { if (!type || !design) return; next = { id: node?.id ?? uid('block'), type: 'block', name: type.name, blockType: type.id, blockDesign: design, allowDesignOverride: allowOverride, fields, slotMappings: mappings } as TemplateBlockNode } if (node) update(next); else create(next) }
  function mapSlot(slot: FieldDefinition) { const old = mappings[slot.key]; if (old) { setMappings(Object.fromEntries(Object.entries(mappings).filter(([key]) => key !== slot.key))); setFields(fields.filter((field) => field.id !== old)); return } const field: TemplateField = { id: uid('field'), type: 'field', fieldType: slot.kind === 'media' ? 'image' : slot.kind === 'textarea' ? 'longText' : slot.kind === 'boolean' ? 'toggle' : 'shortText', label: slot.label, required: !!slot.required }; setFields([...fields, field]); setMappings({ ...mappings, [slot.key]: field.id }) }
  return <section style={panel} aria-label="Configure element"><h2>Configure {item?.label ?? (node?.type === 'field' ? node.label : node?.type === 'block' ? node.name : node?.layout)}</h2>{kind === 'field' && <div><label>Field Label<input aria-label="Field Label" value={label} onChange={(e) => setLabel(e.target.value)} /></label><label><input type="checkbox" checked={required} onChange={(e) => setRequired(e.target.checked)} /> Required</label><label>Help Text<input aria-label="Help Text" value={help} onChange={(e) => setHelp(e.target.value)} /></label><label>Placeholder<input aria-label="Placeholder" value={placeholder} onChange={(e) => setPlaceholder(e.target.value)} /></label><p>Stable identity is generated automatically and survives moving and renaming.</p></div>}{kind === 'layout' && value === 'columns' && <label>Column Layout<select aria-label="Column Layout" value={ratio} onChange={(e) => setRatio(e.target.value)}>{['100','50/50','60/40','40/60','70/30','30/70','33/33/34','50/25/25','25/50/25','25/25/50','25/25/25/25'].map((option) => <option key={option}>{option}</option>)}</select></label>}{kind === 'block' && type && <div><p>Component: <strong>{type.name}</strong></p><label>Design<select aria-label="Design" value={String(design)} onChange={(e) => setDesign(designs.find((option) => String(option.id) === e.target.value)?.id ?? '')}><option value="">Choose Design</option>{designs.filter((option) => String(relationID(option.blockType)) === String(type.id)).map((option) => <option key={option.id} value={String(option.id)}>{option.name}</option>)}</select></label><label><input type="checkbox" checked={allowOverride} onChange={(e) => setAllowOverride(e.target.checked)} /> Allow editor to change Design</label><h3>Hero Content</h3>{(type.fields ?? []).map((slot) => { const mapped = fields.find((field) => field.id === mappings[slot.key]); return <div key={slot.key}><strong>{slot.label}</strong> <button type="button" onClick={() => mapSlot(slot)}>{mapped ? 'Remove mapped field' : 'Add / Map Field'}</button>{mapped && <><label> Field Label<input aria-label={`${slot.label} Field Label`} value={mapped.label} onChange={(event) => setFields(fields.map((field) => field.id === mapped.id ? { ...field, label: event.target.value } : field))} /></label><label><input type="checkbox" checked={!!mapped.required} onChange={(event) => setFields(fields.map((field) => field.id === mapped.id ? { ...field, required: event.target.checked } : field))} /> Required</label></>}</div> })}</div>}<div><button type="button" onClick={finish}>Save Element</button> <button type="button" onClick={cancel}>Cancel</button></div></section>
}
