'use client'
/* eslint-disable react-hooks/refs -- dnd-kit exposes callback refs and reactive drag state as hook return values. */

import { DndContext, KeyboardSensor, PointerSensor, pointerWithin, useDraggable, useDroppable, useSensor, useSensors, type DragEndEvent } from '@dnd-kit/core'
import { sortableKeyboardCoordinates } from '@dnd-kit/sortable'
import { useDocumentInfo, useField, useForm } from '@payloadcms/ui'
import { useEffect, useRef, useState } from 'react'
import { coreEditorElements, editorCategoryLabels, searchEditorElements, toLibraryItem, type EditorElementDefinition, type EditorLibraryItem } from '../editor-registry'
import { insertTemplateNode, moveTemplateNode, moveTemplateNodeTo, removeTemplateNode, updateTemplateNode } from '../template-tree'
import type { FieldDefinition, ID, TemplateBlockNode, TemplateElementStyle, TemplateField, TemplateFieldKind, TemplateLayoutKind, TemplateLayoutNode, TemplateNode } from '../types'

type BlockTypeOption = { id: ID; name: string; description?: string; rendererKey?: string; fields?: FieldDefinition[] }
type DesignOption = { id: ID; name: string; blockType: ID }
type Impact = { collection: string; id: ID; status?: string }
type LegacySection = { key: string; name: string; blockType: ID; blockDesign: ID }
type LibraryItem = EditorLibraryItem
let pendingLibraryPointerItem: LibraryItem | null = null

const layoutItems = coreEditorElements.filter((item) => item.kind === 'layout').map(toLibraryItem)
const fieldItems = coreEditorElements.filter((item) => item.kind === 'field').map(toLibraryItem)
const panel = { border: '1px solid var(--theme-elevation-150)', borderRadius: 8, padding: '1rem' } as const
const relationID = (value: unknown): ID | undefined => typeof value === 'string' || typeof value === 'number' ? value : value && typeof value === 'object' && 'id' in value ? (value as { id?: ID }).id : undefined
const uid = (prefix: string) => `${prefix}_${crypto.randomUUID()}`
const columnRatios = ['100', '50/50', '60/40', '40/60', '70/30', '30/70', '33/33/34', '50/25/25', '25/50/25', '25/25/50', '25/25/25/25']
async function fetchDocs<T>(url: string): Promise<T[]> { const response = await fetch(url, { credentials: 'same-origin' }); if (!response.ok) return []; const body = await response.json() as { docs?: T[] }; return body.docs ?? [] }

function LibraryButton({ item, add }: { item: LibraryItem; add: () => void }) {
  return <div style={{ display: 'flex', gap: 4, marginBottom: 4 }}><button type="button" draggable aria-label={`Drag ${item.label}`} onPointerDown={() => { pendingLibraryPointerItem = item }} onPointerCancel={() => { pendingLibraryPointerItem = null }} onDragStart={(event) => { const serialized = JSON.stringify(item); event.dataTransfer.effectAllowed = 'copy'; event.dataTransfer.setData('application/x-template-library', serialized); event.dataTransfer.setData('text/plain', serialized) }} style={{ cursor: 'grab', touchAction: 'none' }}>⠿</button><button type="button" onClick={add} style={{ flex: 1, textAlign: 'left' }}>{item.label}</button></div>
}
function DropArea({ id, label, children, add, addItem }: { id: string; label: string; children: React.ReactNode; add?: () => void; addItem?: (item: LibraryItem) => void }) {
  const drop = useDroppable({ id: `container:${id}`, data: { containerID: id } })
  return <div style={{ minHeight: 60, padding: 8, border: '1px solid var(--theme-elevation-150)', borderRadius: 6 }}>
    <div ref={drop.setNodeRef} aria-label={label} onPointerUp={() => { if (pendingLibraryPointerItem && addItem) addItem(pendingLibraryPointerItem); pendingLibraryPointerItem = null }} onDragOver={(event) => { event.preventDefault(); event.dataTransfer.dropEffect = 'copy' }} onDrop={(event) => { const value = event.dataTransfer.getData('application/x-template-library') || event.dataTransfer.getData('text/plain'); if (!value || !addItem) return; event.preventDefault(); pendingLibraryPointerItem = null; try { addItem(JSON.parse(value) as LibraryItem) } catch { /* ignore invalid external drag data */ } }} style={{ minHeight: 34, display: 'grid', placeItems: 'center', marginBottom: children ? 8 : 0, border: `1px dashed ${drop.isOver ? 'var(--theme-success-500)' : 'var(--theme-elevation-250)'}`, background: drop.isOver ? 'var(--theme-success-50)' : 'transparent', borderRadius: 6 }}>
      {add && <button type="button" aria-label={`Add element to ${label}`} title={`Add element to ${label}`} onClick={add} style={{ width: 28, height: 28, padding: 0, borderRadius: '50%', fontSize: 18, lineHeight: 1 }}>＋</button>}
    </div>
    {children}
  </div>
}

function ElementPicker({ types, close, choose }: { types: BlockTypeOption[]; close: () => void; choose: (item: LibraryItem) => void }) {
  const [query, setQuery] = useState(''); const [browseAll, setBrowseAll] = useState(false)
  const designed: EditorElementDefinition[] = types.map((type) => ({ kind: 'block', value: String(type.id), label: type.name, description: type.description ?? 'Reusable Designed Block.', category: 'designed', keywords: [type.name.toLowerCase(), 'designed', 'block'] }))
  const available = [...coreEditorElements, ...designed]; const matches = searchEditorElements(available, query); const shown = browseAll || query ? matches : matches.filter((item) => item.frequentlyUsed || item.kind === 'block').slice(0, 6)
  const option = (item: EditorElementDefinition) => <button key={`${item.kind}:${item.value}`} type="button" onClick={() => choose(toLibraryItem(item))} style={{ minHeight: 74, padding: '10px 12px', textAlign: 'left', borderRadius: 6 }}><strong style={{ display: 'block' }}>{item.label}</strong><span style={{ display: 'block', marginTop: 4, color: 'var(--theme-elevation-600)', fontSize: 12 }}>{item.description}</span></button>
  return <div role="presentation" onMouseDown={(event) => { if (event.currentTarget === event.target) close() }} style={{ position: 'fixed', inset: 0, zIndex: 1000, display: 'grid', placeItems: 'center', padding: 24, background: 'rgba(0,0,0,.32)' }}>
    <section role="dialog" aria-modal="true" aria-labelledby="element-picker-title" style={{ ...panel, width: 'min(680px, 100%)', maxHeight: 'min(720px, 85vh)', overflowY: 'auto', background: 'var(--theme-elevation-0)', boxShadow: '0 18px 60px rgba(0,0,0,.24)' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 16 }}><div><h2 id="element-picker-title" style={{ marginBottom: 4 }}>Add an element</h2><p style={{ marginTop: 0 }}>Choose what to place in this area.</p></div><button type="button" aria-label="Close element picker" onClick={close} style={{ width: 32, height: 32, padding: 0 }}>×</button></div>
      <input autoFocus aria-label="Search elements" type="search" placeholder="Search blocks" value={query} onChange={(event) => setQuery(event.target.value)} style={{ width: '100%', marginBottom: 16 }} />
      {!browseAll && !query && <h3>Most used</h3>}
      {browseAll && [...new Set(shown.map((item) => item.category))].map((category) => <section key={category}><h3>{editorCategoryLabels[category]}</h3><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(170px, 1fr))', gap: 8 }}>{shown.filter((item) => item.category === category).map(option)}</div></section>)}
      {!browseAll && <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(170px, 1fr))', gap: 8 }}>{shown.map(option)}</div>}
      {!browseAll && !query && <button type="button" onClick={() => setBrowseAll(true)} style={{ width: '100%', marginTop: 16, padding: 10 }}>Browse all blocks</button>}
      {!shown.length && <p>No blocks match “{query}”.</p>}
    </section>
  </div>
}
type TreeActions = { edit: (node: TemplateNode) => void; move: (id: string, direction: -1 | 1) => void; remove: (id: string) => void; add: (containerID: string) => void; addItem: (item: LibraryItem, containerID: string) => void }
function ListTree({ nodes, actions, selectedID, depth = 0 }: { nodes: TemplateNode[]; actions: TreeActions; selectedID?: string; depth?: number }) {
  return <div role={depth ? 'group' : 'tree'} aria-label={depth ? undefined : 'Template block list'}>{nodes.map((node) => {
    const label = node.type === 'field' ? node.label : node.type === 'block' ? node.name : node.layout === 'columns' ? `Columns ${node.columns?.map((column) => column.width).join('/')}` : node.layout
    return <div key={node.id} role="treeitem" aria-level={depth + 1} aria-selected={selectedID === node.id} style={{ marginLeft: depth * 12 }}><button type="button" onClick={() => actions.edit(node)} style={{ width: '100%', padding: '7px 8px', textAlign: 'left', border: 0, borderBottom: '1px solid var(--theme-elevation-100)', background: selectedID === node.id ? 'var(--theme-elevation-100)' : 'transparent' }}>{node.type === 'layout' ? '▦' : node.type === 'block' ? '◆' : '¶'} {label}</button>{node.type === 'layout' && <>{node.children?.length ? <ListTree nodes={node.children} actions={actions} selectedID={selectedID} depth={depth + 1} /> : null}{node.columns?.map((column, index) => <div key={column.id} style={{ marginLeft: (depth + 1) * 12 }}><div style={{ padding: '5px 8px', color: 'var(--theme-elevation-600)', fontSize: 12 }}>Column {index + 1}</div><ListTree nodes={column.children} actions={actions} selectedID={selectedID} depth={depth + 2} /></div>)}</>}</div>
  })}</div>
}
function Tree({ nodes, actions }: { nodes: TemplateNode[]; actions: TreeActions }) { return <div style={{ display: 'grid', gap: 8 }}>{nodes.map((node) => <CanvasNode key={node.id} node={node} siblings={nodes} actions={actions} />)}</div> }
function CanvasNode({ node, siblings, actions }: { node: TemplateNode; siblings: TemplateNode[]; actions: TreeActions }) {
  const drag = useDraggable({ id: `node:${node.id}`, data: { nodeID: node.id } }); const index = siblings.findIndex((item) => item.id === node.id)
  const title = node.type === 'field' ? node.label : node.type === 'block' ? node.name : node.layout
  const controls = <div style={{ display: 'flex', gap: 4, flexWrap: 'wrap' }}><button type="button" {...drag.listeners} {...drag.attributes} aria-label={`Drag ${title}`}>⠿</button><button type="button" aria-label={`Edit ${title}`} onClick={() => actions.edit(node)}>Edit</button><button type="button" disabled={index <= 0} onClick={() => actions.move(node.id, -1)}>Move Up</button><button type="button" disabled={index === siblings.length - 1} onClick={() => actions.move(node.id, 1)}>Move Down</button><button type="button" onClick={() => actions.remove(node.id)}>Remove</button></div>
  if (node.type === 'field') return <article ref={drag.setNodeRef} style={panel}><strong>{node.label}</strong><p>{fieldItems.find((item) => item.value === node.fieldType)?.label}{node.required ? ' · Required' : ''}</p>{controls}</article>
  if (node.type === 'block') return <article ref={drag.setNodeRef} style={panel}><strong>{node.name}</strong><p>Designed Block · {node.fields.length} mapped field{node.fields.length === 1 ? '' : 's'}</p>{controls}</article>
  return <article ref={drag.setNodeRef} style={panel}><strong>{node.layout === 'columns' ? `Columns · ${node.columns?.map((column) => column.width).join(' / ')}` : title}</strong>{controls}{node.layout === 'columns' ? <div style={{ display: 'grid', gridTemplateColumns: node.columns?.map((column) => `${column.width}fr`).join(' '), gap: 8, marginTop: 8 }}>{node.columns?.map((column, i) => <DropArea key={column.id} id={column.id} label={`Column ${i + 1}`} add={() => actions.add(column.id)} addItem={(item) => actions.addItem(item, column.id)}><Tree nodes={column.children} actions={actions} /></DropArea>)}</div> : !['spacer', 'divider'].includes(node.layout) ? <div style={{ marginTop: 8 }}><DropArea id={node.id} label={`${node.layout} contents`} add={() => actions.add(node.id)} addItem={(item) => actions.addItem(item, node.id)}><Tree nodes={node.children ?? []} actions={actions} /></DropArea></div> : null}</article>
}

export function TemplateBuilder({ configuredCollections = ['posts'], registeredRendererKeys = ['hero-board'] }: { configuredCollections?: string[]; registeredRendererKeys?: string[] }) {
  const { id, hasPublishedDoc } = useDocumentInfo(); const { submit, disabled } = useForm()
  const nameField = useField<string>({ path: 'name' }); const descriptionField = useField<string>({ path: 'description' }); const slugField = useField<string>({ path: 'slug' }); const collectionsField = useField<string[]>({ path: 'allowedCollections' }); const layoutField = useField<TemplateNode[]>({ path: 'layout' }); const sectionsField = useField<LegacySection[]>({ path: 'sections' }); const statusField = useField<string>({ path: '_status' })
  const name = nameField.value ?? ''; const collections = Array.isArray(collectionsField.value) ? collectionsField.value : []; const nodes = Array.isArray(layoutField.value) ? layoutField.value : []; const legacy = Array.isArray(sectionsField.value) ? sectionsField.value : []
  const [types, setTypes] = useState<BlockTypeOption[]>([]); const [designs, setDesigns] = useState<DesignOption[]>([]); const [impact, setImpact] = useState<Impact[]>([]); const [editing, setEditing] = useState<TemplateNode | null>(null); const [adding, setAdding] = useState<LibraryItem | null>(null); const [target, setTarget] = useState('root'); const [libraryTarget, setLibraryTarget] = useState('root'); const [libraryOpen, setLibraryOpen] = useState(true); const [libraryMode, setLibraryMode] = useState<'blocks' | 'list'>('blocks'); const [pickerTarget, setPickerTarget] = useState<string | null>(null); const [error, setError] = useState<string | null>(null)
  const modified = useRef(false); const sensors = useSensors(useSensor(PointerSensor), useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates }))
  useEffect(() => { Promise.all([
    fetchDocs<BlockTypeOption>('/api/design-block-types?depth=0&limit=100&where[status][equals]=published&where[_status][equals]=published'),
    fetchDocs<DesignOption>('/api/design-block-designs?depth=0&limit=100&where[status][equals]=published&where[_status][equals]=published'),
  ]).then(([typeDocs, designDocs]) => { setTypes(typeDocs.filter((item) => item.rendererKey && registeredRendererKeys.includes(item.rendererKey))); setDesigns(designDocs) }).catch(() => setError('Could not load the registered design library.')) }, [registeredRendererKeys])
  useEffect(() => { if (!id) return
    async function load() { try { const response = await fetch(`/api/design-templates/${id}?draft=true&depth=0`, { credentials: 'same-origin' }); const doc = response.ok ? await response.json() as { layout?: TemplateNode[]; sections?: LegacySection[] } : null; if (!modified.current) { if (Array.isArray(doc?.layout)) layoutField.setValue(doc.layout); if (Array.isArray(doc?.sections)) sectionsField.setValue(doc.sections) } } catch { /* keep current form data */ }
      try { const response = await fetch(`/api/design-templates/${id}/dependencies`, { credentials: 'same-origin' }); const body = response.ok ? await response.json() as Impact[] : []; setImpact(Array.isArray(body) ? body : []) } catch { setImpact([]) } }
    void load()
  }, [id, layoutField, sectionsField])
  const setNodes = (next: TemplateNode[]) => { modified.current = true; layoutField.setValue(next) }
  const startAdd = (item: LibraryItem, container = 'root') => { setAdding(item); setTarget(container); setEditing(null) }
  const openPickerFor = (containerID: string) => setPickerTarget(containerID)
  const actions: TreeActions = { edit: (node) => { setEditing(node); setAdding(null) }, add: openPickerFor, addItem: (item, containerID) => startAdd(item, containerID), move: (nodeID, direction) => setNodes(moveTemplateNode(nodes, nodeID, direction)), remove: (nodeID) => { if (!hasPublishedDoc || !impact.length || window.confirm(`This Template is used by ${impact.length} content items. Removed field values remain stored. Continue?`)) setNodes(removeTemplateNode(nodes, nodeID)) } }
  function dragEnd(event: DragEndEvent) { const container = event.over?.data.current?.containerID as string | undefined; if (!container) return; const library = event.active.data.current?.library as LibraryItem | undefined; if (library) startAdd(library, container); else { const nodeID = event.active.data.current?.nodeID as string | undefined; if (nodeID) setNodes(moveTemplateNodeTo(nodes, nodeID, container)) } }
  async function save(publish: boolean) { if (!name.trim() || !collections.length) { setError('Name and Use With are required.'); return } await submit({ overrides: { slug: slugField.value || name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''), status: publish ? 'published' : 'draft', _status: publish ? 'published' : 'draft' } }) }
  return <DndContext id="template-builder-dnd" sensors={sensors} collisionDetection={pointerWithin} onDragEnd={dragEnd}><div data-testid="template-builder" style={{ display: 'grid', gap: 16 }}><header><h1>{name || 'Create Template'}</h1><strong>{statusField.value === 'published' ? 'Published' : 'Draft'}</strong>{id && <p>Used by: {impact.length} content item{impact.length === 1 ? '' : 's'}</p>}</header>
    <section style={panel}><label>Name<input aria-label="Name" value={name} onChange={(e) => nameField.setValue(e.target.value)} /></label><label style={{ display: 'grid', gap: 6, marginTop: 12 }}>Description<textarea aria-label="Description" value={descriptionField.value ?? ''} onChange={(e) => descriptionField.setValue(e.target.value)} style={{ display: 'block', width: '100%', minHeight: 88, resize: 'vertical' }} /></label><fieldset style={{ marginTop: 12 }}><legend>Use With</legend>{configuredCollections.map((slug) => <label key={slug}><input type="checkbox" checked={collections.includes(slug)} onChange={() => collectionsField.setValue(collections.includes(slug) ? collections.filter((item) => item !== slug) : [...collections, slug])} /> {slug[0].toUpperCase() + slug.slice(1)}</label>)}</fieldset></section>
    <div><button type="button" aria-expanded={libraryOpen} aria-controls="template-element-library" onClick={() => { setLibraryTarget('root'); setLibraryOpen((open) => !open) }}>☰ {libraryOpen ? 'Close' : 'Open'} Element Library</button></div>
    <div style={{ display: 'grid', gridTemplateColumns: libraryOpen ? '240px minmax(0, 1fr) minmax(280px, 360px)' : 'minmax(0, 1fr) minmax(280px, 360px)', gap: 16, alignItems: 'start' }}>
      {libraryOpen && <aside id="template-element-library" style={{ ...panel, position: 'sticky', top: 16, maxHeight: 'calc(100vh - 32px)', overflowY: 'auto' }} aria-label="Element Library"><div style={{ display: 'flex', justifyContent: 'space-between', gap: 8 }}><h2>{libraryMode === 'blocks' ? 'Block Library' : 'List View'}</h2><button type="button" aria-label="Close Element Library" onClick={() => setLibraryOpen(false)}>×</button></div><div role="tablist" aria-label="Editor sidebar" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 4, marginBottom: 12 }}><button role="tab" aria-selected={libraryMode === 'blocks'} type="button" onClick={() => setLibraryMode('blocks')}>Blocks</button><button role="tab" aria-selected={libraryMode === 'list'} type="button" onClick={() => setLibraryMode('list')}>List View</button></div>{libraryMode === 'list' ? <ListTree nodes={nodes} actions={actions} selectedID={editing?.id} /> : <><p>Add to: <strong>{libraryTarget === 'root' ? 'Template Canvas' : 'selected container'}</strong></p><h3>Layout</h3>{layoutItems.map((item) => <LibraryButton key={item.value} item={item} add={() => startAdd(item, libraryTarget)} />)}<h3>Fields</h3>{fieldItems.map((item) => <LibraryButton key={item.value} item={item} add={() => startAdd(item, libraryTarget)} />)}<h3>Designed Blocks</h3>{types.map((type) => { const item: LibraryItem = { kind: 'block', value: String(type.id), label: type.name }; return <LibraryButton key={type.id} item={item} add={() => startAdd(item, libraryTarget)} /> })}</>}</aside>}
      <main aria-label="Template Canvas"><h2>Template Canvas</h2><DropArea id="root" label="Template Canvas drop area" add={() => openPickerFor('root')} addItem={(item) => startAdd(item, 'root')}>{!nodes.length && !legacy.length && <p style={{ textAlign: 'center', color: 'var(--theme-elevation-600)' }}>Add the first element to this Template.</p>}<Tree nodes={nodes} actions={actions} />{legacy.length > 0 && <section><h3>Existing Designed Blocks</h3>{legacy.map((section) => <article key={section.key} style={panel}><strong>{section.name}</strong><p>Legacy live reference retained. Rebuild on the canvas when ready.</p></article>)}</section>}</DropArea></main>
      <aside aria-label="Configure panel" style={{ ...panel, position: 'sticky', top: 16 }}><h2>Configure</h2>{(adding || editing) ? <NodeEditor item={adding} node={editing} types={types} designs={designs} cancel={() => { setAdding(null); setEditing(null) }} create={(node) => { setNodes(insertTemplateNode(nodes, target, node)); setAdding(null); setLibraryTarget('root') }} update={(node) => { setNodes(updateTemplateNode(nodes, node.id, () => node)); setEditing(null) }} /> : <p>Select Edit on an element, drag an item from the library, or use an Add element button.</p>}</aside>
    </div>
    {pickerTarget && <ElementPicker types={types} close={() => setPickerTarget(null)} choose={(item) => { startAdd(item, pickerTarget); setPickerTarget(null) }} />}
    {error && <p role="alert">{error}</p>}<footer><button type="button" disabled={disabled} onClick={() => void save(false)}>Save Draft</button> <button type="button" disabled={disabled} onClick={() => void save(true)}>{hasPublishedDoc ? 'Publish Changes' : 'Publish Template'}</button></footer></div></DndContext>
}

function NodeEditor({ item, node, types, designs, cancel, create, update }: { item: LibraryItem | null; node: TemplateNode | null; types: BlockTypeOption[]; designs: DesignOption[]; cancel: () => void; create: (node: TemplateNode) => void; update: (node: TemplateNode) => void }) {
  const kind = item?.kind ?? node?.type; const value = item?.value ?? (node?.type === 'field' ? node.fieldType : node?.type === 'layout' ? node.layout : node?.type === 'block' ? String(relationID(node.blockType)) : '')
  const [label, setLabel] = useState(node?.type === 'field' ? node.label : item?.label ?? ''); const [required, setRequired] = useState(node?.type === 'field' && !!node.required); const [help, setHelp] = useState(node?.type === 'field' ? node.helpText ?? '' : ''); const [placeholder, setPlaceholder] = useState(node?.type === 'field' ? node.placeholder ?? '' : '')
  const [ratio, setRatio] = useState(node?.type === 'layout' && node.layout === 'columns' ? node.columns?.map((column) => column.width).join('/') ?? '50/50' : '50/50'); const type = types.find((option) => String(option.id) === value); const block = node?.type === 'block' ? node : null
  const [design, setDesign] = useState<ID | ''>(relationID(block?.blockDesign) ?? ''); const [allowOverride, setAllowOverride] = useState(!!block?.allowDesignOverride); const [fields, setFields] = useState<TemplateField[]>(block?.fields ?? []); const [mappings, setMappings] = useState<Record<string, string>>(block?.slotMappings ?? {})
  const [tab, setTab] = useState<'settings' | 'style' | 'advanced'>('settings'); const [style, setStyle] = useState<TemplateElementStyle>(node?.style ?? {})
  function finish() { let next: TemplateNode; if (kind === 'layout') { const layout = value as TemplateLayoutKind; const oldColumns = node?.type === 'layout' && node.layout === 'columns' ? node.columns ?? [] : []; next = { id: node?.id ?? uid('layout'), type: 'layout', layout, style, ...(layout === 'columns' ? { columns: ratio.split('/').map((width, index) => ({ id: oldColumns[index]?.id ?? uid('column'), width: Number(width), children: oldColumns[index]?.children ?? [] as TemplateNode[] })) } : ['spacer', 'divider'].includes(layout) ? {} : { children: node?.type === 'layout' ? node.children ?? [] : [] as TemplateNode[] }) } as TemplateLayoutNode } else if (kind === 'field') next = { id: node?.id ?? uid('field'), type: 'field', fieldType: value as TemplateFieldKind, label: label || item?.label || 'Untitled', required, helpText: help, placeholder, style } as TemplateField; else { if (!type || !design) return; next = { id: node?.id ?? uid('block'), type: 'block', name: type.name, blockType: type.id, blockDesign: design, allowDesignOverride: allowOverride, fields, slotMappings: mappings, style } as TemplateBlockNode } if (node) update(next); else create(next) }
  function mapSlot(slot: FieldDefinition) { const old = mappings[slot.key]; if (old) { setMappings(Object.fromEntries(Object.entries(mappings).filter(([key]) => key !== slot.key))); setFields(fields.filter((field) => field.id !== old)); return } const field: TemplateField = { id: uid('field'), type: 'field', fieldType: slot.kind === 'media' ? 'image' : slot.kind === 'textarea' ? 'longText' : slot.kind === 'boolean' ? 'toggle' : 'shortText', label: slot.label, required: !!slot.required }; setFields([...fields, field]); setMappings({ ...mappings, [slot.key]: field.id }) }
  const control = { display: 'grid', gap: 6 } as const
  const tabButton = (name: typeof tab, text: string) => <button type="button" role="tab" aria-selected={tab === name} onClick={() => setTab(name)} style={{ padding: '9px 6px', border: 0, borderBottom: tab === name ? '2px solid var(--theme-success-500)' : '2px solid transparent', background: 'transparent' }}>{text}</button>
  return <section aria-label="Configure element"><h2 style={{ marginTop: 0 }}>Configure {item?.label ?? (node?.type === 'field' ? node.label : node?.type === 'block' ? node.name : node?.layout)}</h2><div role="tablist" aria-label="Element settings" style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', marginBottom: 18, borderBottom: '1px solid var(--theme-elevation-150)' }}>{tabButton('settings', kind === 'layout' ? 'Layout' : 'Settings')}{tabButton('style', 'Style')}{tabButton('advanced', 'Advanced')}</div>
    {tab === 'settings' && kind === 'field' && <div style={{ display: 'grid', gap: 14 }}><label style={control}><span>Field label</span><input aria-label="Field Label" value={label} onChange={(e) => setLabel(e.target.value)} style={{ width: '100%' }} /></label><label style={{ display: 'flex', gap: 8, alignItems: 'center' }}><input type="checkbox" checked={required} onChange={(e) => setRequired(e.target.checked)} /> Required</label><label style={control}><span>Help text</span><textarea aria-label="Help Text" value={help} onChange={(e) => setHelp(e.target.value)} rows={3} style={{ width: '100%', resize: 'vertical' }} /></label><label style={control}><span>Placeholder</span><input aria-label="Placeholder" value={placeholder} onChange={(e) => setPlaceholder(e.target.value)} style={{ width: '100%' }} /></label><p style={{ margin: 0, color: 'var(--theme-elevation-600)', fontSize: 12 }}>This element keeps the same stable identity when it is renamed or moved.</p></div>}
    {tab === 'settings' && kind === 'layout' && value === 'columns' && <div><h3 style={{ marginTop: 0 }}>Choose a variation</h3><div role="radiogroup" aria-label="Column Layout" style={{ display: 'grid', gridTemplateColumns: 'repeat(2, minmax(0, 1fr))', gap: 8 }}>{columnRatios.map((option) => <button key={option} type="button" role="radio" aria-checked={ratio === option} onClick={() => setRatio(option)} style={{ padding: 10, border: ratio === option ? '2px solid var(--theme-success-500)' : '1px solid var(--theme-elevation-250)', borderRadius: 6, background: ratio === option ? 'var(--theme-elevation-100)' : 'transparent' }}><span aria-hidden="true" style={{ display: 'grid', gridTemplateColumns: option.split('/').map((width) => `${width}fr`).join(' '), gap: 3, height: 30, marginBottom: 6 }}>{option.split('/').map((_, index) => <span key={index} style={{ display: 'block', border: '1px solid currentColor', borderRadius: 2 }} />)}</span>{option}</button>)}</div></div>}
    {tab === 'settings' && kind === 'layout' && value !== 'columns' && <p>Use the Style tab to control this layout’s presentation.</p>}
    {tab === 'settings' && kind === 'block' && type && <div style={{ display: 'grid', gap: 14 }}><p>Component: <strong>{type.name}</strong></p><label style={control}><span>Design</span><select aria-label="Design" value={String(design)} onChange={(e) => setDesign(designs.find((option) => String(option.id) === e.target.value)?.id ?? '')} style={{ width: '100%' }}><option value="">Choose Design</option>{designs.filter((option) => String(relationID(option.blockType)) === String(type.id)).map((option) => <option key={option.id} value={String(option.id)}>{option.name}</option>)}</select></label><label style={{ display: 'flex', gap: 8, alignItems: 'center' }}><input type="checkbox" checked={allowOverride} onChange={(e) => setAllowOverride(e.target.checked)} /> Allow editor to change Design</label><h3>Content mapping</h3>{(type.fields ?? []).map((slot) => { const mapped = fields.find((field) => field.id === mappings[slot.key]); return <section key={slot.key} style={{ ...panel, padding: 10 }}><strong>{slot.label}</strong> <button type="button" onClick={() => mapSlot(slot)}>{mapped ? 'Remove mapped field' : 'Add / Map Field'}</button>{mapped && <div style={{ display: 'grid', gap: 10, marginTop: 10 }}><label style={control}><span>Field label</span><input aria-label={`${slot.label} Field Label`} value={mapped.label} onChange={(event) => setFields(fields.map((field) => field.id === mapped.id ? { ...field, label: event.target.value } : field))} /></label><label><input type="checkbox" checked={!!mapped.required} onChange={(event) => setFields(fields.map((field) => field.id === mapped.id ? { ...field, required: event.target.checked } : field))} /> Required</label></div>}</section> })}</div>}
    {tab === 'style' && <div style={{ display: 'grid', gap: 14 }}><SelectSetting label="Width" value={style.width ?? 'content'} options={['content', 'wide', 'full']} change={(width) => setStyle({ ...style, width: width as TemplateElementStyle['width'] })} /><SelectSetting label="Alignment" value={style.alignment ?? 'left'} options={['left', 'center', 'right']} change={(alignment) => setStyle({ ...style, alignment: alignment as TemplateElementStyle['alignment'] })} /><SelectSetting label="Spacing" value={style.spacing ?? 'medium'} options={['none', 'small', 'medium', 'large']} change={(spacing) => setStyle({ ...style, spacing: spacing as TemplateElementStyle['spacing'] })} /><SelectSetting label="Background" value={style.background ?? 'transparent'} options={['transparent', 'surface', 'muted', 'accent']} change={(background) => setStyle({ ...style, background: background as TemplateElementStyle['background'] })} />{kind === 'field' && <><SelectSetting label="Text color" value={style.textColor ?? 'default'} options={['default', 'muted', 'accent', 'inverse']} change={(textColor) => setStyle({ ...style, textColor: textColor as TemplateElementStyle['textColor'] })} /><SelectSetting label="Font size" value={style.fontSize ?? 'medium'} options={['small', 'medium', 'large', 'xlarge']} change={(fontSize) => setStyle({ ...style, fontSize: fontSize as TemplateElementStyle['fontSize'] })} /></>}</div>}
    {tab === 'advanced' && <div style={{ display: 'grid', gap: 14 }}><label style={control}><span>HTML anchor</span><input aria-label="HTML Anchor" value={style.anchor ?? ''} onChange={(event) => setStyle({ ...style, anchor: event.target.value.replace(/[^a-zA-Z0-9_-]/g, '') })} /></label><label style={control}><span>Additional CSS class</span><input aria-label="Additional CSS Class" value={style.cssClass ?? ''} onChange={(event) => setStyle({ ...style, cssClass: event.target.value })} /></label><p style={{ margin: 0, color: 'var(--theme-elevation-600)', fontSize: 12 }}>Stable element ID: {node?.id ?? 'created when saved'}</p></div>}
    <div style={{ display: 'flex', gap: 8, marginTop: 18 }}><button type="button" onClick={finish}>Save Element</button><button type="button" onClick={cancel}>Cancel</button></div>
  </section>
}

function SelectSetting({ label, value, options, change }: { label: string; value: string; options: string[]; change: (value: string) => void }) {
  return <label style={{ display: 'grid', gap: 6 }}><span>{label}</span><select aria-label={label} value={value} onChange={(event) => change(event.target.value)}>{options.map((option) => <option key={option} value={option}>{option[0].toUpperCase() + option.slice(1)}</option>)}</select></label>
}
